config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#index'

  # Users
  get '/sign_up', to: 'sign_up#new'
  post '/sign_up', to: 'sign_up#create'
  get '/log_in', to: 'sessions#new'
  post '/log_in', to: 'sessions#create'
  delete '/log_out', to: 'sessions#destroy'
  resources :users, only: %i[edit update]

  # Search
  get '/search', to: 'search#index'

  # Filter
  get '/filter', to: 'filter#index'

  # Current Location
  get '/current_location', to: 'current_location#find'

  # Coffee Shop
  get '/coffee_shop', to: 'coffee_shop#show'
  post '/favorite', to: 'coffee_shop#favorite'
  delete '/favorite', to: 'coffee_shop#destroy'

  # Google Oauth
  get '/auth/:provider/callback' => 'sessions#omniauth'
end

app/controllers/search_controller.rb
# frozen_string_literal: true

class SearchController < ApplicationController
  before_action :location, only: [:index]

  def index
    @pagy, @coffee_shops = pagy_array(SearchFacade.route(location))
  rescue StandardError
    redirect_to root_path(current_location: 'Please try a different location!')
  end

  private

  def location
    if params[:query]
      session[:location] = params[:query]
    else
      session[:location]
    end
  end

  def search_params
    params.permit(:query, :sort_by, :price, :button)
  end
end

app/views/search/_coffee_shops.html.erb
<div class="filtered_coffee_shops">
    <% coffee_shops.each do |c| %>
		<%= image_tag c.image_url.to_s, height: "200", width: "250" %>
		<p><%= link_to c.name, coffee_shop_path(yelp_id: c.id) %></p>
		<p>Rating: <%= c.rating %></p>
		<p>Location: <%= c.formatted_location %></p>
		<p>Phone: <%= c.phone %></p>

		<% if c.open %>
			<p>Currently Open</p>
		<% else %>
			<p>Currently Closed</p>
		<% end %>
	<% end%>
	<hr>
</div>

app/views/search/_drop_down.html.erb
<%= form_tag filter_path, method: :get do %>
	<%= select_tag(:sort_by, options_for_select(["No Starbucks","Rating", "Price"])) %>
	<%= submit_tag "Filter" %>
<% end %>

app/views/search/_zipcode_search.html.erb
<div id="zipcode_search">
	<%= form_with url: "/search", method: :get, multipart: true do |form| %>
	<%= form.label :query, "Where would you like to grab coffee?" %>
	<%= form.text_field :query %>
	<%= form.submit "Search" %>
<% end %><br>
</div>

app/views/search/index.html.erb
<center>
	<h1>Caffeination</h1>
	<hr>
	<%== pagy_bootstrap_nav(@pagy) %>
	<%= render partial: "drop_down", locals: {coffee_shops: @coffee_shops} %><br>
	<%= render partial: "coffee_shops", locals: {coffee_shops: @coffee_shops}, cached: true %>
</center>