config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#index'

  # Users
  get '/sign_up', to: 'sign_up#new'
  post '/sign_up', to: 'sign_up#create'
  get '/log_in', to: 'sessions#new'
  post '/log_in', to: 'sessions#create'
  delete '/log_out', to: 'sessions#destroy'
  resources :users, only: %i[edit update]

  # Search
  get '/search', to: 'search#index'

  # Filter
  get '/filter', to: 'filter#index'

  # Current Location
  get '/current_location', to: 'current_location#find'

  # Coffee Shop
  get '/coffee_shop', to: 'coffee_shop#show'
  post '/favorite', to: 'coffee_shop#favorite'
  delete '/favorite', to: 'coffee_shop#destroy'

  # Google Oauth
  get '/auth/:provider/callback' => 'sessions#omniauth'
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @current_location = begin
      params[:current_location]
    rescue StandardError
      nil
    end
    @favorite_spots = begin
      FindService.find_favorite_spots(current_user.email)
    rescue StandardError
      nil
    end
  end
end

app/views/home/_current_location.html.erb
<div id="current_location">
	<%= form_with url: "/current_location", method: :get, multipart: true do |form| %>
	<%= button_tag(type: 'submit', class: "btn btn-outline-secondary", title: "Find Current Location") do %>
		<i class="fas fa-map-marker-alt"></i>
	<% end %>
<% end %>
</div>

app/views/home/_favorite_spots.html.erb
<div id="favorite_spots">
	<h5>My Favorite Spots: </h5>
		<% if Rails.env.production? && favorite_spots %>
			<% favorite_spots.each do |spot| %>
				<p><%= link_to spot.name, coffee_shop_path(yelp_id: spot.yelp_id) %></p>
			<% end %>
		<% end %>
</div>

app/views/home/_recommended_spots.html.erb
<div id="recommended_spots">
	<h5>Recommended Spots: </h5>
	<%# Need to add logic for recommending spots to a user %>
</div>

app/views/home/_user_information.html.erb
<div id="user_information">
	<h5>Welcome <%= current_user.username %></h5>
</div>

app/views/home/_user_options.html.erb
<div id="user_options">
	<% if logged_in %>
		<%= button_to 'Log out', log_out_path, class: "btn btn-outline-secondary", method: :delete %>
		<%# add button to log out or refer a friend %>
	<% else %>
		<%= button_to 'Log in', log_in_path, class: "btn btn-outline-secondary", method: :get %><br>
		<%= button_to 'Sign up', sign_up_path, class: "btn btn-outline-secondary", method: :get %><br>
	<% end %>
</div>

app/views/home/_zipcode.html.erb
<div id="zipcode_search">
  <%= form_with url: "/search", method: :get do |form| %>
  <%= form.label :query, "Where would you like to grab coffee?" %>
  <%= form.text_field :query %>
  <%= form.submit "Search" %>
<% end %>
</div>

app/views/home/_zipcode_search_form.html.erb
<div id="zipcode_search">
	<%= form_with url: "/search", method: :get, html: { class: "search_form" }, multipart: true do |form| %>
		<div class="mb-3">
			<%= form.label :query, "Where would you like to grab coffee?" %><br><br>
        <% if location == "Please try a different location!" %>
          <%= form.text_field :query, placeholder: "Please try a different location!", class: "form-control" %>
        <% elsif location  %>
          <%= form.text_field :query, value: location || "Enter a location!", class: "form-control" %>
        <% else %>
          <%= form.text_field :query, placeholder: "Enter a location!", class: "form-control" %>
        <% end %>
			<br>
        <%= button_tag(type: 'submit', class: "btn btn-outline-secondary", title: "Search for Coffee Spots") do %>
          <i class="fas fa-mug-hot"></i>
        <% end %>
		</div>
	<% end %>
</div>

app/views/home/index.html.erb
<main>
  <div class="px-4 py-5 my-5 text-center">
  	<img src=<%=asset_path("pexels-adrian-regeci-9942543.jpg")%> height=300 width=200 alt="Hipster Coffee Stuff">
      <h1 class="display-5 fw-bold">CAFFEINATION</h1>
        <div class="col-lg-6 mx-auto">
          <p class="lead mb-4">Find, save and share your favorite coffee spots!</p>
            <% if logged_in %>
              <%= render "user_information" %>
          <% end %>
        <br>
      <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
          <%= render partial: "zipcode_search_form", locals: { location: @current_location } %>
      </div>
        <%= render "current_location" %>
      </div>
    </div>
</main>

app/views/home/index.html.haml
.main
  .div.home-content
    = image_tag(asset_path("pexels-adrian-regeci-9942543.jpg"), class: "pic")
    %h1
      CAFFEINATION
      .div
        %p
          Find, save and share your favorite coffee spots!