config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#index'

  # Users
  get '/sign_up', to: 'sign_up#new'
  post '/sign_up', to: 'sign_up#create'
  get '/log_in', to: 'sessions#new'
  post '/log_in', to: 'sessions#create'
  delete '/log_out', to: 'sessions#destroy'
  resources :users, only: %i[edit update]

  # Search
  get '/search', to: 'search#index'

  # Filter
  get '/filter', to: 'filter#index'

  # Current Location
  get '/current_location', to: 'current_location#find'

  # Coffee Shop
  get '/coffee_shop', to: 'coffee_shop#show'
  post '/favorite', to: 'coffee_shop#favorite'
  delete '/favorite', to: 'coffee_shop#destroy'

  # Google Oauth
  get '/auth/:provider/callback' => 'sessions#omniauth'
end

app/models/coffee_shop.rb
# frozen_string_literal: true

require 'open-uri'

class CoffeeShop < ApplicationRecord
  has_and_belongs_to_many :users

  has_one_attached :yelp_image

  before_save :attach_yelp_image

  validates :coordinates, presence: true
  validates :location, presence: true

  def attach_yelp_image
    return if image_url.nil?

    filename = image_url
    downloaded_image = URI.open image_url

    yelp_image.attach(io: downloaded_image, filename: filename)
  end

  def formatted_location
    location['display_address'].join(' ')
  end

  class << self
    def filter_by_rating(location)
      all.where(search_phrase: location).order(rating: :desc)
    end

    def translate_to_model(coffee_shops)
      results = []

      CoffeeShop.transaction do
        coffee_shops.each do |cf|
          coffee_shop = CoffeeShop.find_by_yelp_id cf.yelp_id

          coffee_shop ||= CoffeeShop.find_or_create_by(
            name: cf.name,
            coordinates: cf.coordinates,
            location: cf.location,
            image_url: cf.image_url.to_s,
            rating: cf.rating,
            transaction_types: cf.transaction_types,
            phone: cf.phone,
            url: cf.url,
            search_phrase: cf.search_phrase,
            yelp_id: cf.yelp_id,
            open: cf.is_open?,
            price: cf.price,
            hours: cf.hours
          )
          results << coffee_shop
        end
      end

      results
    end
  end
end

app/controllers/coffee_shop_controller.rb
# frozen_string_literal: true

class CoffeeShopController < ApplicationController
  def show
    @coffee_shop = CoffeeShop.find(params[:yelp_id])
    @is_favorite = current_user&.find_favorite(@coffee_shop) || false
  end

  def favorite
    yelp_id = params[:format]
    result = Yelp::Fetch.call(yelp_id: yelp_id).result

    if result
      coffee_shop = CoffeeShop.find_or_create_by(
        name: result.name,
        coordinates: result.coordinates,
        location: result.location,
        image_url: result.image_url.to_s,
        rating: result.rating,
        transaction_types: result.transaction_types,
        phone: result.phone,
        url: result.url,
        search_phrase: result.search_phrase,
        yelp_id: result.yelp_id,
        open: result.is_open?,
        price: result.price,
        hours: result.hours
      )
    end

    if coffee_shop && current_user
      current_user.coffee_shops << coffee_shop

      flash[:notice] = "#{coffee_shop.name} has been added to your favorite Coffee Shops!"
    else
      flash[:notice] = 'An error occurred, please try again'
    end
    redirect_back(fallback_location: root_path)
  end

  def destroy
    yelp_id = params[:format]

    if user
      response = DestroyService.destroy_favorite(user.dig(:data, :id), yelp_id)
      user = {
        type: :user,
        event: :destroy,
        id: user.dig(:data, :id),
        email: user.dig(:data, :attributes, :email),
        coffee_shop: {
          yelp_id: yelp_id
        }
      }
      LogCreateJob.perform_later(user)
      flash[:notice] = if response == 'success'
                         'Favorite has been removed!'
                       else
                         'An error occurred, please try again'
                       end
    else
      flash[:notice] = 'An error occurred, please try again'
    end
    redirect_back(fallback_location: root_path)
  end
end

app/views/coffee_shop/_coffee_shop.html.erb
<div class="coffee_shop">
	<h3><%=coffee_shop.name %></h3>
		<hr>
			<%= image_tag coffee_shop.image_url.to_s, height: "200", width: "250" %>
		<br>
	<br>
		<% if logged_in %>
			<% if is_favorite == false %>
				<div class="favorite_button">
					<%= form_with url: favorite_path(coffee_shop.yelp_id), method: :post, multipart: true do |form| %>
						<%= button_tag(type: 'submit', class: "btn btn-outline-secondary", title: "Favorite") do %>
							<i class="fas fa-star"></i>
						<% end %>
					<% end %>
				</div>
			<% else %>
				<div class="remove_favorite_button">
					<%= form_with url: favorite_path(coffee_shop.yelp_id), method: :delete, multipart: true do |form| %>
						<%= button_tag(type: 'submit', class: "btn btn-outline-secondary", title: "Remove Favorite") do %>
							<i class="fas fa-minus-circle"></i>
						<% end %>
					<% end %>
				</div>
			<% end %>
		<% end %>
	<br>
		<p>Rating: <%= coffee_shop.rating %></p>
		<p>Location: <%= coffee_shop.formatted_location %></p>
		<p>View on Yelp: <%= link_to "#{coffee_shop.name}", coffee_shop.url %></p>
		<p>Phone: <%= coffee_shop.phone %></p>
	<hr>
</div>

app/views/coffee_shop/show.html.erb
<main>
  <div class="px-4 py-5 my-5 text-center">
	  <%= render partial: "coffee_shop", locals: { coffee_shop: @coffee_shop, is_favorite: @is_favorite } %>
  </div>
</main>