config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#index'

  # Users
  get '/sign_up', to: 'sign_up#new'
  post '/sign_up', to: 'sign_up#create'
  get '/log_in', to: 'sessions#new'
  post '/log_in', to: 'sessions#create'
  delete '/log_out', to: 'sessions#destroy'
  resources :users, only: %i[edit update]

  # Search
  get '/search', to: 'search#index'

  # Filter
  get '/filter', to: 'filter#index'

  # Current Location
  get '/current_location', to: 'current_location#find'

  # Coffee Shop
  get '/coffee_shop', to: 'coffee_shop#show'
  post '/favorite', to: 'coffee_shop#favorite'
  delete '/favorite', to: 'coffee_shop#destroy'

  # Google Oauth
  get '/auth/:provider/callback' => 'sessions#omniauth'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>CaffeinationFe</title>
		<meta name="viewport" content="width=device-width,initial-scale=1">
		<%= csrf_meta_tags %>
		<%= csp_meta_tag %>

		<%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
	</head>

	<body>

		<nav class="navbar navbar-expand-lg navbar-light bg-light">
		<div class="container-fluid">
			<div class="container">
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav me-auto mb-2 mb-lg-0">
				<li class="nav-item">
					<%= link_to icon("fa", "home"), root_path, method: :get, class: "nav-link active" %>
				</li>
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
						<i class="fa fa-user-circle" aria-hidden="true"></i>
					</a>
					<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
						<% if logged_in %>
							<%= link_to "Settings", edit_user_path(current_user), method: :get, class: "dropdown-item" %>
							<%= link_to "Log Out", log_out_path, method: :delete, class: "dropdown-item" %>
						<% else %>
							<%= link_to "Log In", log_in_path, method: :get, class: "dropdown-item" %>
							<%= link_to "Log In with Google", "/auth/google_oauth2", method: :post, class: "dropdown-item" %>

							<li><hr class="dropdown-divider"></li>
							<%= link_to "Sign Up", sign_up_path, method: :get, class: "dropdown-item" %>
						<% end %>
					</ul>
				</li>
				<% if !current_page?(root_path) %>
					<li class="nav-item">
						<%= link_to "Back", :back, class: "nav-link active" %>
					</li>
				<% end %>
				</ul>
			</div>
			</div>
		</div>
		</nav>

		<div class="container">

		<% flash.each do |name, message| %>
			<%= message %>
		<% end %>

		<%= yield %>
		<div>
	</body>
</html>